### ISSUE TITLE
bunka.get_topics

### ISSUE THREAD

**Issue by thepinkclimate** [charlesdedampierre/BunkaTopics#49]
Hello there,
I successfully embed and create topics, but when I get to bunka.get_topics to extract them I get the following error message which I cannot solve nor understand. What is the problem? Tahnk you!

2024-03-07 17:44:14 - Bunka - INFO - Computing the topics
INFO:Bunka:Computing the topics
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-41-b0c24dcda3f7>](https://localhost:8080/#) in <cell line: 2>()
      1 # Get the list of topics
----> 2 df_topics = bunka.get_topics(n_clusters = 15, name_length=5, min_count_terms = 2)
      3 df_topics = df_topics[['topic_id', 'name', 'size']].copy()

4 frames
[/usr/local/lib/python3.10/dist-packages/pandas/core/reshape/reshape.py](https://localhost:8080/#) in unstack(obj, level, fill_value, sort)
    504             return _unstack_frame(obj, level, fill_value=fill_value, sort=sort)
    505         else:
--> 506             return obj.T.stack(future_stack=True)
    507     elif not isinstance(obj.index, MultiIndex):
    508         # GH 36113

TypeError: DataFrame.stack() got an unexpected keyword argument 'future_stack'

**Comment by charlesdedampierre** [comment]
Hi!

What version of pandas do you have?
Have you tried: min_count_terms = 1 ? 
How much data do you have ?

Charles

**Comment by thepinkclimate** [comment]
Hello Charles,

I changed now the pandas version to 1.5.3 as I am using CoLab, but it is
still giving me the same error.
I have a list of 8037 abstracts so I do not think we are talking about a
huge number of data points.

**Comment by charlesdedampierre** [comment]
Hello, 

I think the issue comes from your version of pandas. The one in BunkaTopics is 2.2.1 and yours is 1.5.3. I thinks this is due to google-colab which is associated with this older version of pandas.

After installing bunkatopics as the following line on the colab:
!pip install pandas --upgrade

This will  upgrade your pandas versions

You an test on this notebook
https://colab.research.google.com/drive/11K5bKs4y6snEFEZhKFNuNVRRSAsq9b7p#scrollTo=1EItWnn51Sc5, 

Hope this helps, 

Charles

**Comment by thepinkclimate** [comment]
Dear Charles,

thank you. it works now.
I am facing a new issue which I do not seem capable of solving.
When I launch the Mistral model to use LLM to assign names of my topics, I
obtained the prompt itself + a name.

I checked with bunka.df_topics_
finding exactly the same. I think that "name" is now "topic_name" and that
may be the reason.

I thank you for your support with this.

Best regards,
Francesca

**Comment by charlesdedampierre** [comment]
Hi Francesca, 

Yes this is indeed a bug I will solve soon !

For the moment, the best way to quickly get clean topic names is either to use Open ai or to change them manually as explained here: https://charlesdedampierre.github.io/BunkaTopics/topic_exploration.html#topic-modeling-with-genai-summarization-of-topics

Very sorry for the inconvenience, I hope to release soon a new version free of issues like this one, 

Charles

**Comment by thepinkclimate** [comment]
Thank you Charles,

I am glad this time I was helpful :)

Can I use LLAMA instead? Or does the library work exclusively with Mistral
and Open AI?

Best regards,
Francesca

**Comment by charlesdedampierre** [comment]
The time I fix the bug, I suggest you only use OpenAI or manually change the labels. In the future, indeed it will be possible to use any model to carry out the different tasks.

Charles

**Comment by thepinkclimate** [comment]
Dear Charles,
thank you for coming back to me and for fixing the issue.

I see that now the topics are retrieved but the figures cannot be generated
as they cause the sudden session interruption and restart (I am talking
about the CoLab sessions).

Thank you for your work, very much appreciated.

Best regards,
Francesca

**Comment by charlesdedampierre** [comment]
the Colab works well here: https://colab.research.google.com/drive/11K5bKs4y6snEFEZhKFNuNVRRSAsq9b7p#scrollTo=pwwvRKB0Bm_o

How many documents are you talking about ? Can you give a screenshot ?

Charles

**Comment by thepinkclimate** [comment]
Dear Charles,

the code runs well but the figure is not produced as the runtime
disconnects when I hit bunka.visualize_topics. It does it everytime and I
suspect it is because of numerosity. May I be right?
I am talking about a file of 156334 elements in docs.

Thank you,
Francesca

**Comment by charlesdedampierre** [comment]
Hello Francesca, 

We launched a new version with some bugs that are fixes (like the topic names) and new capabilities like coloring the map based on a category. 

We are still working on use cases with bigger data, I will keep you in touch when we advance on the subject, 

Best, 

Charles

**Comment by thepinkclimate** [comment]
Thank you Charles,

I am going to give it a try and come back to you just for feedback!

Thanks!
Francesca
