### ISSUE TITLE
Missing ipywidget depency when `pip install bunkatopics`

### ISSUE THREAD

**Issue by mariusmercier** [charlesdedampierre/BunkaTopics#50]
Just installed bunkatopics and get this message error. I guess you may have forgotten the ipywidget in the dependency list
![image](https://github.com/charlesdedampierre/BunkaTopics/assets/101870075/5aa67534-525a-4271-99b6-983720eb0f0c)

**Comment by charlesdedampierre** [comment]
Great thanks, I will add it for the next release !
