### ISSUE TITLE
pb dans le notebook bourdieu

### ISSUE THREAD

**Issue by altomator** [charlesdedampierre/BunkaTopics#8]
Bonjour Charles,

J'obtiens cette erreur : 

Creating new labels for clusters:   0%|          | 0/10 [00:00<?, ?it/s]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-26-69bfc80565b4>](https://localhost:8080/#) in <cell line: 13>()
     11                     }
     12 
---> 13 bourdieu_fig = bunka.visualize_bourdieu(
     14     generative_model=llm,
     15     x_left_words=["this is a positive content"],

12 frames

[/usr/local/lib/python3.10/dist-packages/langchain/llms/huggingface_hub.py](https://localhost:8080/#) in _call(self, prompt, stop, run_manager, **kwargs)
    112         response = self.client(inputs=prompt, params=params)
    113         if "error" in response:
--> 114             raise ValueError(f"Error raised by inference API: {response['error']}")
    115         if self.client.task == "text-generation":
    116             # Text generation return includes the starter text.

ValueError: Error raised by inference API: Internal Server Error

**Comment by charlesdedampierre** [comment]
Hi, 

Thanks for the feedback. 

are you talking about this notebook? https://github.com/charlesdedampierre/BunkaTopics/blob/main/notebooks/pipeline_front_end_bourdieu.ipynb

What type of generative_model did you chose ?

Charles

**Comment by altomator** [comment]
Hi,

I just opened the Visual Topic Modeling With Bunkatopics / Open in Colab
link and ran it without any change.

Best,

JP

**Comment by charlesdedampierre** [comment]
Hi, 

I found the mistake, the LLM used was not the good one for Bourdieu Analysis was not the good one.

This model works for both: llm = HuggingFaceHub(repo_id = 'mistralai/Mistral-7B-Instruct-v0.1', huggingfacehub_api_token = hf_token)

Here is the updated notebook, that should work.

https://colab.research.google.com/drive/1DtPrI82TYepWLoc4RwuQnOqMJb0eWT_t?usp=sharing

Thanks again for spotting the mistake, 

Charles

**Comment by altomator** [comment]
Bonjour,

Merci beaucoup pour le correctif.
Je me demandais quels modèles utiliser pour traiter des textes en français ?

Bien cordialement,

jp

**Comment by charlesdedampierre** [comment]
Bonjour, 

Vous trouverez tout dans la documentation du README.md dans la version multilangue. 

Cdt
